Add management for configs

diff --git a/configs/zshrc b/configs/zshrc
--- a/configs/zshrc
+++ b/configs/zshrc
@@ -1,7 +1,13 @@
+# Useful variable definitions
 export LANG=en_US.UTF-8
 export EDITOR='nvim'
 export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
 export ZSH="$HOME/.oh-my-zsh"
+
+# Personal Directories
+export CONFIG_DIR="$HOME/Config"
+export NVIM_DIR="$CONFIG_DIR/Neovim"
+export MANAGED_CONFIG_DIR="$CONFIG_DIR/Main/configs"
 
 ZSH_THEME="spaceship"
 CASE_SENSITIVE="true"
@@ -60,3 +66,48 @@ source $HOME/.cargo/env
 #     # Try to attach to an existing tmux session; if none, create a new one
 #     tmux attach || exec tmux
 # fi
+
+# Function to move and manage config directories as needed
+manage() {
+    if [ $# -ne 1 ]; then
+        echo "Usage: manage <config file or dir>"
+        return 1
+    fi
+
+    local src="$(readlink -f "$1")"
+    local dst="$(readlink -f "$MANAGED_CONFIG_DIR")"
+    local src_name="$(basename "$src")"
+    local dst_path="$dst/$src_name"
+
+    mv -n "$src" "$dst_path" || {
+        echo "Failed to move $src to $dst"
+        return 2
+    }
+
+    ln -s "$dst_path" "$src" || {
+        echo "Failed to create symlink $src -> $dst"
+        return 3
+    }
+
+    local CWD="$(pwd)"
+
+    # Determine if we should commit this newly managed config.
+    if [ read -q "choice?Would you like to commit this directory? [n]: "; then
+        cd "$dst_path"
+        git add .
+        git commit -m "Begin managing $src_name config"
+        cd "$CWD"
+    else
+        echo
+        echo "Not commiting config to repo."
+    fi
+
+    # Determine if user would like to move to the config dir
+    if [ read -q "choice?Would you like to move to the config directory? [n]: "; then
+        cd "$dst_path"
+    else
+        echo "Not leaving current directory."
+    fi
+
+    return 0
+}
